=== imCodePartnerAB/imcms/src/main/resources/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="schema">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="init" minOccurs="1" maxOccurs="1"/>
          <xs:element ref="diffs" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute name="version" type="xs:double" use="required"/>
      </xs:complexType>
    </xs:element>

    <xs:element name="init">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="script" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>

        <xs:attribute name="version" type="xs:double" use="required"/>
      </xs:complexType>
    </xs:element>

    <xs:element name="diffs">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="diff" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>


    <xs:element name="diff">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="script" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>

        <xs:attribute name="from" type="xs:double" use="required"/>
        <xs:attribute name="to" type="xs:double" use="required"/>
      </xs:complexType>
    </xs:element>


    <xs:element name="script" type="xs:string"/>
    
</xs:schema>

=== imCodePartnerAB/imcms/src/main/resources/schema.xml
<schema version="6.23"
        xsi:noNamespaceSchemaLocation="schema.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <init version="4.11">
        <script>imcms_4.11.sql</script>
    </init>

    <diffs>
        <diff from="4.8" to="4.9">
            <script>diff/diff-4.8-4.9-mysql.sql</script>
        </diff>
        <diff from="4.9" to="4.10">
            <script>diff/diff-4.9-4.10-mysql.sql</script>
        </diff>
        <diff from="4.10" to="4.11">
            <script>diff/diff-4.10-4.11-mysql.sql</script>
        </diff>
        <diff from="4.11" to="4.12">
            <script>diff/diff-4.11-4.12-mysql.sql</script>
        </diff>
        <diff from="4.12" to="4.13">
            <script>diff/diff-4.12-4.13-mysql.sql</script>
        </diff>
        <diff from="4.13" to="4.14">
            <script>diff/diff-4.13-4.14-mysql.sql</script>
        </diff>
        <diff from="4.14" to="4.15">
            <script>diff/diff-4.14-4.15-mysql.sql</script>
        </diff>
        <diff from="4.15" to="4.16">
            <script>diff/diff-4.15-4.16-mysql.sql</script>
        </diff>
        <diff from="4.16" to="6.2">
            <script>diff/diff-4.16-6.2-mysql.sql</script>
        </diff>
        <diff from="6.2" to="6.3">
            <script>diff/diff-6.2-6.3-mysql.sql</script>
        </diff>
        <diff from="6.3" to="6.4">
            <script>diff/diff-6.3-6.4-mysql.sql</script>
        </diff>
        <diff from="6.4" to="6.5">
            <script>diff/diff-6.4-6.5-mysql.sql</script>
        </diff>
        <diff from="6.5" to="6.6">
            <script>diff/diff-6.5-6.6-mysql.sql</script>
        </diff>
        <diff from="6.6" to="6.7">
            <script>diff/diff-6.6-6.7-mysql.sql</script>
        </diff>
        <diff from="6.7" to="6.8">
            <script>diff/diff-6.7-6.8-mysql.sql</script>
        </diff>
        <diff from="6.8" to="6.9">
            <script>diff/diff-6.8-6.9-mysql.sql</script>
        </diff>
        <diff from="6.9" to="6.10">
            <script>diff/diff-6.9-6.10-mysql.sql</script>
        </diff>
        <diff from="6.10" to="6.11">
            <script>diff/diff-6.10-6.11-mysql.sql</script>
        </diff>
        <diff from="6.11" to="6.12">
            <script>diff/diff-6.11-6.12-mysql.sql</script>
        </diff>
        <diff from="6.12" to="6.13">
            <script>diff/diff-6.12-6.13-mysql.sql</script>
        </diff>
        <diff from="6.13" to="6.14">
            <script>diff/diff-6.13-6.14-mysql.sql</script>
        </diff>
        <diff from="6.14" to="6.15">
            <script>diff/diff-6.14-6.15-mysql.sql</script>
        </diff>
        <diff from="6.15" to="6.16">
            <script>diff/diff-6.15-6.16-mysql.sql</script>
        </diff>
        <diff from="6.16" to="6.17">
            <script>diff/diff-6.16-6.17-mysql.sql</script>
        </diff>
        <diff from="6.17" to="6.18">
            <script>diff/diff-6.17-6.18-mysql.sql</script>
        </diff>
        <diff from="6.18" to="6.19">
            <script>diff/diff-6.18-6.19-mysql.sql</script>
        </diff>
        <diff from="6.19" to="6.20">
            <script>diff/diff-6.19-6.20-mysql.sql</script>
        </diff>
        <diff from="6.20" to="6.21">
            <script>diff/diff-6.20-6.21-mysql.sql</script>
        </diff>
        <diff from="6.21" to="6.22">
            <script>diff/diff-6.21-6.22-mysql.sql</script>
        </diff>
        <diff from="6.22" to="6.23">
            <script>diff/diff-6.22-6.23-mysql.sql</script>
        </diff>
    </diffs>
</schema>
